// 获取比赛列表
export const GET_COMPETITON_LIST = 'GET_COMPETITON_LIST'

// 报名比赛
export const SET_ATTEND_FAILURE = 'SET_ATTEND_FAILURE'

// 获取比赛列表失败
export const GET_COMPETITON_LIST_FAILURE = 'GET_COMPETITON_LIST_FAILURE'

// 获取比赛详情
export const GET_COMPETITON_INTRO = 'GET_COMPETITON_INTRO'

// 获取比赛详情失败
export const GET_COMPETITON_INTRO_FAILURE = 'GET_COMPETITON_INTRO_FAILURE'

// 获取参加比赛人员列表
export const GET_COMPETITON_MEMBER = 'GET_COMPETITON_MEMBER'

// 获取参加比赛人员列表失败
export const GET_COMPETITON_MEMBER_FAILURE = 'GET_COMPETITON_MEMBER_FAILURE'

// 获取对阵列表
export const GET_COMPETITON_AGAINST = 'GET_COMPETITON_AGAINST'

// 获取对阵列表失败
export const GET_COMPETITON_AGAINST_FAILURE = 'GET_COMPETITON_AGAINST_FAILURE'

// 获取当前用户比赛信息
export const GET_COMPETITON_USER = 'GET_COMPETITON_USER'

// 获取当前用户比赛信息失败
export const GET_COMPETITON_USER_FAILURE = 'GET_COMPETITON_USER_FAILURE'

// 获取当前比赛类型
export const GET_COMPETITON_TYPE = 'GET_COMPETITON_TYPE'

// 获取对阵详情
export const GET_AGAINST_DETAIL = 'GET_AGAINST_DETAIL'
