// 获取比赛列表
export const GET_COMPETITON_LIST = 'GET_COMPETITON_LIST'

// 获取比赛列表失败
export const GET_COMPETITON_LIST_FAILURE = 'GET_COMPETITON_LIST_FAILURE'

// 获取比赛详情
export const GET_COMPETITON_INTRO = 'GET_COMPETITON_INTRO'

// 获取比赛详情失败失败
export const GET_COMPETITON_INTRO_FAILURE = 'GET_COMPETITON_INTRO_FAILURE'
